name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_ACCESS_TOKEN }}
          expo-cache: true

      - name: Install app dependencies
        run: yarn --prefer-offline

      - name: Build ANDROID on EAS
        id: expo_build
        run: npx eas-cli build --platform android --profile development --non-interactive 

      - name: Echo output 1
        run: echo ${{ steps.expo_build.outputs.stdout }}

      - name: Echo output 2
        run: echo ${{ steps.expo_build.outputs }}

      - name: Echo output 3
        run: echo ${{ steps.expo_build.outputs.* }}
